import type { Metadata } from "next";
import HomeLink from "@/components/HomeLink";
import { Bungee, Manrope, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const displayFont = Bungee({
  variable: "--font-display",
  subsets: ["latin", "latin-ext"],
  weight: ["400"],
});

const bodyFont = Manrope({
  variable: "--font-body",
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700"],
});

const monoFont = JetBrains_Mono({
  variable: "--font-code",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${displayFont.variable} ${bodyFont.variable} ${monoFont.variable} antialiased`}
      >
        <div className="relative">
          <HomeLink />
          {children}
        </div>
      </body>
    </html>
  );
}
